var t1 = ["Ukuran <b><p>wiremesh</b> diukur berdasarkan diameter tulangan dan ditandai dengan awalan `M`. Contohnya, M6 mengacu pada <b><p>wiremesh</b> dengan diameter tulangan 6 mm. Anda dapat menemukan <b><p>wiremesh</b> dengan berbagai ukuran diameter seperti M4, M5, M6, M7, M8, M9, M10, dan M12. Selain itu, terdapat dua jenis <b><p>wiremesh</b> yang umum digunakan, yaitu lembaran dan gulungan (roll).",
"<b><p>Ukuran Besi Wiremesh 10mm</b><br/>Ini adalah ukuran diameter besi yang dipakai untuk bikin wiremesh. Biasanya dipakai untuk beragam aplikasi, kayak bikin pagar, lantai, atau dinding. Ukuran besinya adalah 10 mm, ada juga yang dengan toleransi hingga aktualnya adalah diameter 9,7 mm atau 9,5 mm. Tanyakan pada penjual, diameter aktualnya. Kemudian minta dijelaskan bagaimana cara pengukurannya, dan silakan diukur sendiri menggunakan sketmat, atau jangka sorong.</p>",
"<b><p>Ukuran Lobang Wiremesh</b><br/>Ini mengacu pada jarak antar besi di wiremesh. Jarak lobang wiremesh bisa disesuaikan sesuai kebutuhan. Jarak standar wiremesh yang biasa digunakan untuk kebutuhan kostruksi atau struktur beton bertulang adalah 15 cm x 15 cm. Jika menggunakan satuan milimeter, maka menjadi 150 mm x 150 mm. Di Jayasteel dan Mitranya menyediakan yang ukuran lubang standar ini, jika anda ada permintaan ukuran lubang wiremesh yang lain, anda bisa memesannya untuk diproduksi khusus sesuai kebutuhan anda.</p>",
"<b><p>Jenis Wiremesh</b><br/>Ada wiremesh polos dan wiremesh ulir. Wiremesh polos punya permukaan yang halus, sementara wiremesh ulir punya permukaan yang beralur. Berdasarkan panjangnya dibedakan dalam wiremesh lembaran dan roll atau guluangan. Wiremesh yang standarnya adalah lebar 2,1 meter, untuk jenis bentuk lembaran, panjangnya adalah 5,4 meter, sedangkan untuk yang jenis bentuk gulungan panjangnya adalah 54 meter. Ada lagi jenis wiremesh yang dibedakan dalam jumlah besi membujur dan melintangnya, yakni wiremesh standar dan wiremesh overhang. Apa itu <a href='https://www.jayasteel.com/2015/08/wiremesh-overhang-pinggit-tertutup-dan.html' target='_blank'>wiremesh overhang</a>, kamu bisa cek tulisan lain di web Jayasteel.com.</p>",
"<b><p>Wiremesh Ulir</b><br/>Ini tipe wiremesh yang permukaannya beralur. Lebih kuat dan tahan lama daripada wiremesh polos. Sering digunakan buat aplikasi yang butuh daya tahan tinggi, seperti pagar, lantai, atau dinding. Bentuk ulir bertujuan untuk dapat mengikat lebih kuat pada beton. Tidak mudah selip ketika mengalami beban tarik di dalam konstruksi beton bertulang. Ada beberapa jenis atau bentuk ulir, dengan tujuan dan fungsi yang sama. Rata-rata hanya variasi saja, tanpa mengurangi kekuatan.</p>",
"<b><p>Wiremesh Lebar</b><br/>Ini wiremesh yang lebih lebar dari yang biasa. Cocok dipakai buat area besar, kayak pagar, lantai, atau dinding. Lebar standar wiremesh untuk kebutuhan konstruksi adalah 2,1 meter. Standar ini juga disesuaikan dengan ukuran standar kontainer dan truk. Sehingga mudah dalam pengangkutan. Bahkan wiremesh yang lebarnya 2,1 meter itu, yang dalam bentuk roll, menjadi mudah diangkut menggunakan kendaraan kecil sekalipun, misalnya pickup.</p>",
"<b><p>Wiremesh M8 150</b><br/>Ini tipe wiremesh dengan diameter besi 8mm dan jarak antar besi 150mm. Dipakai lumayan umum buat berbagai aplikasi, kayak bikin pagar, lantai, atau dinding. Ukuran ini juga yang paling banyak diproduksi. Dan biasanya digunakan sebagai patokan harga per kg dalam perhitungan penjualan. Untuk ukuran lebih besar, biasanya sedikit lebih mahal per kg-nya, demikian juga untuk ukuran yang lebih kecil. Ukuran lain yang sering digunakan adalah wiremesh M6.</p>",
"<b><p>Mutu Wiremesh</b><br/>Kualitas wiremesh ditentukan sama bahan dan proses buatnya. Yang bagus biasanya punya daya tahan dan kekuatan tinggi.&nbsp;Kawat baja yang digunakan adalah dari mutu U-50 dengan tegangan leleh karakteristik 5000 kg /cm2, sedangkan tegangan geser minimum tiap titik las adalah 2500 kg/cm2.</p>",
"<b><p>Panjang Wiremesh M8</b><br/>Panjangnya bisa disesuaikan dengan kebutuhan. Untuk panjang standar ada yang panjang standar 5,4 meter yang dalam bentuk lembaran atau 54 meter untuk yang bentuk gulungan atau roll. Ada banyak pilihan wiremesh di Jayasteel, mulai dari ukuran, jenis, sampe kualitasnya. Plus, juga bisa kirim ke seluruh Indonesia.</p>"];
document.write(t1[Math.floor((Math.abs(new Date().getTime() - new Date(2023, 6, 11).getTime()) / 39e6) % t1.length)]);
