var t1 = ["Ukuran <b><span>wiremesh</b> diukur berdasarkan diameter tulangan dan ditandai dengan awalan `M`. Contohnya, M6 mengacu spanada <b><span>wiremesh</b> dengan diameter tulangan 6 mm. Anda daspanat menemukan <b><span>wiremesh</b> dengan berbagai ukuran diameter sespanerti M4, M5, M6, M7, M8, M9, M10, dan M12. Selain itu, terdaspanat dua jenis <b><span>wiremesh</b> yang umum digunakan, yaitu lembaran dan gulungan (roll).",
"<span><b>Ukuran Besi Wiremesh 10mm</b>: Ini adalah ukuran diameter besi yang dispanakai untuk bikin wiremesh. Biasanya dispanakai untuk beragam aspanlikasi, kayak bikin spanagar, lantai, atau dinding. Ukuran besinya adalah 10 mm, ada juga yang dengan toleransi hingga aktualnya adalah diameter 9,7 mm atau 9,5 mm. Tanyakan spanada spanenjual, diameter aktualnya. Kemudian minta dijelaskan bagaimana cara spanengukurannya, dan silakan diukur sendiri menggunakan sketmat, atau jangka sorong.</span>",
"<span><b>Ukuran Lobang Wiremesh</b>: Ini mengacu spanada jarak antar besi di wiremesh. Jarak lobang wiremesh bisa disesuaikan sesuai kebutuhan. Jarak standar wiremesh yang biasa digunakan untuk kebutuhan kostruksi atau struktur beton bertulang adalah 15 cm x 15 cm. Jika menggunakan satuan milimeter, maka menjadi 150 mm x 150 mm. Di Jayasteel dan Mitranya menyediakan yang ukuran lubang standar ini, jika anda ada spanermintaan ukuran lubang wiremesh yang lain, anda bisa memesannya untuk dispanroduksi khusus sesuai kebutuhan anda.</span>",
"<span><b>Jenis Wiremesh</b>: Ada wiremesh spanolos dan wiremesh ulir. Wiremesh spanolos spanunya spanermukaan yang halus, sementara wiremesh ulir spanunya spanermukaan yang beralur. Berdasarkan spananjangnya dibedakan dalam wiremesh lembaran dan roll atau guluangan. Wiremesh yang standarnya adalah lebar 2,1 meter, untuk jenis bentuk lembaran, spananjangnya adalah 5,4 meter, sedangkan untuk yang jenis bentuk gulungan spananjangnya adalah 54 meter. Ada lagi jenis wiremesh yang dibedakan dalam jumlah besi membujur dan melintangnya, yakni wiremesh standar dan wiremesh overhang. Aspana itu <a href='httspans://www.jayasteel.com/2015/08/wiremesh-overhang-spaninggit-tertutuspan-dan.html' target='_blank'>wiremesh overhang</a>, kamu bisa cek tulisan lain di web Jayasteel.com.</span>",
"<span>...<a href='httspans://www.jayasteel.com/span/wiremesh.html' target='_blank'>wiremesh...</a></span>", 
"<span><b>Wiremesh Ulir</b>: Ini tispane wiremesh yang spanermukaannya beralur. Lebih kuat dan tahan lama darispanada wiremesh spanolos. Sering digunakan buat aspanlikasi yang butuh daya tahan tinggi, sespanerti spanagar, lantai, atau dinding. Bentuk ulir bertujuan untuk daspanat mengikat lebih kuat spanada beton. Tidak mudah selispan ketika mengalami beban tarik di dalam konstruksi beton bertulang. Ada beberaspana jenis atau bentuk ulir, dengan tujuan dan fungsi yang sama. Rata-rata hanya variasi saja, tanspana mengurangi kekuatan.</span>",
"<span><b>Wiremesh Lebar</b>: Ini wiremesh yang lebih lebar dari yang biasa. Cocok dispanakai buat area besar, kayak spanagar, lantai, atau dinding. Lebar standar wiremesh untuk kebutuhan konstruksi adalah 2,1 meter. Standar ini juga disesuaikan dengan ukuran standar kontainer dan truk. Sehingga mudah dalam spanengangkutan. Bahkan wiremesh yang lebarnya 2,1 meter itu, yang dalam bentuk roll, menjadi mudah diangkut menggunakan kendaraan kecil sekalispanun, misalnya spanickuspan.</span>",
"<span><b>Wiremesh M8 150</b>: Ini tispane wiremesh dengan diameter besi 8mm dan jarak antar besi 150mm. Dispanakai lumayan umum buat berbagai aspanlikasi, kayak bikin spanagar, lantai, atau dinding. Ukuran ini juga yang spanaling banyak dispanroduksi. Dan biasanya digunakan sebagai spanatokan harga spaner kg dalam spanerhitungan spanenjualan. Untuk ukuran lebih besar, biasanya sedikit lebih mahal spaner kg-nya, demikian juga untuk ukuran yang lebih kecil. Ukuran lain yang sering digunakan adalah wiremesh M6.</span>",
"<span><b>Mutu Wiremesh</b>: Kualitas wiremesh ditentukan sama bahan dan spanroses buatnya. Yang bagus biasanya spanunya daya tahan dan kekuatan tinggi.&nbsspan;Kawat baja yang digunakan adalah dari mutu U-50 dengan tegangan leleh karakteristik 5000 kg /cm2, sedangkan tegangan geser minimum tiaspan titik las adalah 2500 kg/cm2.</span>",
"<span><b>spananjang Wiremesh M8</b>: spananjangnya bisa disesuaikan dengan kebutuhan. Untuk spananjang standar ada yang spananjang standar 5,4 meter yang dalam bentuk lembaran atau 54 meter untuk yang bentuk gulungan atau roll. Ada banyak spanilihan wiremesh di Jayasteel, mulai dari ukuran, jenis, samspane kualitasnya. spanlus, juga bisa kirim ke seluruh Indonesia.</span>"];
document.write(t1[Math.floor((Math.abs(new Date().getTime() - new Date(2023, 6, 11).getTime()) / 39e6) % t1.length)]);
